### ISSUE TITLE
Accessing non-existent key returns table, not nil

### ISSUE THREAD

**Issue by abevol** [SGG-Modding/Chalk#1]
I tried upgrading from Chalk-1.0.0 to Chalk-2.0.2 for my mod. 
When I accessed a non-existent key in the configuration file, it didn't return nil as previous versions or as typically expected from a Lua table, but instead, it returned a table. 
However, when I tried to access this table using ipairs(tbl), I received an error:
`SGG_Modding-Chalk\main.lua:59: bad argument #1 to 'next' (table expected, got userdata)`

Here is my test code:
```lua
---@module 'config'
Config = Chalk.auto 'plugins/config.lua'

print(string.format("Config.Enabled: %s, %s", type(Config.Enabled), tostring(Config.Enabled)))
print(string.format("Config.absdadf: %s", type(Config.absdadf)))
print(string.format("Config[\"absdadf\"]: %s", type(Config["absdadf"])))
for index, value in ipairs(Config.absdadf) do
    print(string.format("index: %s, value: %s", tostring(index), tostring(value)))
end
```
And Output log:
```log
[05:59:16.4391037][INFO/log.cpp:30] Abevol-MultiReward: [MultiReward] Config.Enabled: boolean, true
[05:59:16.4393100][INFO/log.cpp:30] Abevol-MultiReward: [MultiReward] Config.absdadf: table
[05:59:16.4394798][INFO/log.cpp:30] Abevol-MultiReward: [MultiReward] Config["absdadf"]: table
[05:59:16.4396900][FATAL/lua_manager.cpp:311] ...\Ship\ReturnOfModding\plugins\SGG_Modding-Chalk\main.lua:81: bad argument #1 to 'next' (table expected, got userdata)
stack traceback:
        [C]: in function 'next'
        ...\Ship\ReturnOfModding\plugins\SGG_Modding-Chalk\main.lua:81: in function 'for iterator'
        ...urnOfModding\plugins\Abevol-MultiReward\plugins\main.lua:51: in function 'on_ready'
        ...Ship\ReturnOfModding\plugins\SGG_Modding-ReLoad\main.lua:21: in function <...Ship\ReturnOfModding\plugins\SGG_Modding-ReLoad\main.lua:15>
        (...tail calls...)
        ...urnOfModding\plugins\Abevol-MultiReward\plugins\main.lua:70: in function 'v'
        ...hip\ReturnOfModding\plugins\SGG_Modding-ModUtil\main.lua:51: in function 'trigger_ready_final'
        ...hip\ReturnOfModding\plugins\SGG_Modding-ModUtil\main.lua:24: in function <...hip\ReturnOfModding\plugins\SGG_Modding-ModUtil\main.lua:22>
```

My mod needs to know whether the desired key exists in the configuration file (as my mod allows players to create keys in the configuration file themselves).However, according to the current behavior of Chalk-2.0.2, I can't obtain this information at all. If the key does not exist, it would return an empty table, yet it's nearly impossible for me to know that it's an empty table through just about any means. The only method is for me to assume the players would follow my rules and create a key I designate, so that I can ascertain if this is a valid table. But this is only effective when the value is a table.. I would still hope that, like before, if a non-existing key is accessed, it directly returns nil.

**Comment by AndreLouisIssa** [comment]
This is intended behaviour.
The wrapped config it returns is just an interface into the real config, which it only evaluates lazily.

The real config is the second value returned by chalk.auto(), to use it you must read [Hell2Modding's docs](https://github.com/SGG-Modding/Hell2Modding/blob/master/docs/lua/classes/rom.config.config_file.md)

In order to know if a key is nil ahead of time, I would have to verify that no entries with a section that has that key as a descendant (starts with the path string) exist, so config access would become O(n) where n is on the order of entries, or rather O(nm) for m the average length of a section.

Furthermore, it's valid that one may use the wrapped config to define new sections through a merge operation, or directly through the real config, and they should remain interlinked.

**Comment by AndreLouisIssa** [comment]
However, I could define `__len` or `__call` such that it returns nil if the table is not yet created, and that is what you could use to check. So it would work like:

```lua
---@module 'config'
Config = Chalk.auto 'plugins/config.lua'

Config.absdadf -- type: table
#Config.absdadf -- type: nil

Config.absdadf[1] = 2
#Config.absdadf -- type: number
```

or

```lua
---@module 'config'
Config = Chalk.auto 'plugins/config.lua'

Config.absdadf -- type: table
Config.absdadf() -- type: nil

Config.absdadf[1] = 2
Config.absdadf() -- type: table
```

or, I expose a function to check

```lua
---@module 'config'
Config = Chalk.auto 'plugins/config.lua'

Config.absdadf -- type: table
Chalk.exists(Config.absdadf) -- return: false

Config.absdadf[1] = 2
Chalk.exists(Config.absdadf) -- return: true
```

Or, how else would you like to be able to check it?

**Comment by AndreLouisIssa** [comment]
the `SGG_Modding-Chalk\main.lua:59: bad argument #1 to 'next' (table expected, got userdata)` part is actually an issue with Hell2Modding, but I think I can get around it, I'll make a separate issue for it.

**Comment by AndreLouisIssa** [comment]
ah, I already do have to loop over all entries for access, to fix this would just be to iterate twice, alright, I'll do it.

**Comment by abevol** [comment]
Thank you for the reply! 
I just want to emphasize once again, in case I haven't made myself clear, or you overlooked it, we not only need to know whether the table-type key exists, but also whether other types of keys exist.

My thought is, since we are already simulating a table, why don't we make it more like one? Unless returning an empty table has other benefits.

By the way, I solved my problem by rewriting the code.
Considering my actual requirements might give you a reference for your improvements.
This was the previous code:
```lua
local function getRewardCount(config, rewardType, lootName)
    local v = config[rewardType] or config["Others"]
    if type(v) == "table" then
        v = v[lootName] or v["Others"]
    end
    return v or 1
end
```
This is the code after rewriting:
```lua
local function getRewardCount(config, rewardType, lootName)
    local v = config[rewardType]
    if type(v) == "table" then
        v = v[lootName]
        if type(v) ~= "number" then
            v = v["Others"]
        end
    end
    if type(v) ~= "number" then
        v = config["Others"]
    end
    if type(v) ~= "number" then
        v = 1
    end
    return v
end
```
And it seems that the rewritten code is more robust, it seems I had my own problem too. 😂

**Comment by AndreLouisIssa** [comment]
@abevol can you contact me on Discord so we can discuss more rapid development?

My Username: magic_gonads
My User ID: 156353015635378176
Hades Modding Server: https://discord.gg/KuMbyrN
